
# Ticket detection (fallbacks if host plugin doesn't set a PDC tag)
ticket:
  name: "&e가방 확장권"
  lore-contains:
    - "&77칸씩 확장"
    - "&79칸 페이지 생성"
  pdc-keys:
    - "ultimate:bag_ticket"   # 예: 네임스페이스:key 형식

pager:
  title: "&6가방 &7(Page {page})"
