
ticket:
  name: "&e가방 확장권"
  # Display name keywords that also count as a ticket (fallback)
  name-keywords:
    - "확장권"
    - "ticket"
    - "bag"
  # Any lore line containing one of the following (after color-strip) makes it a ticket
  lore-contains:
    - "9칸"
    - "확장"
  # Optional PDC keys that also mark tickets
  pdc-keys:
    - "ultimate:bag_ticket"

pager:
  title: "&6가방 &7(Page {page})"
