name: Java CI (UltimateBackpack, module=backpack)
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: 'maven'
      - name: Build
        run: |
          mvn -B -DskipTests -f backpack/pom.xml clean package
          echo "== JARs =="
          find backpack -maxdepth 3 -type f -name "*.jar" -print
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UltimateBackpack-jar
          path: backpack/target/*.jar
          if-no-files-found: error
