name: Java CI (UltimateBackpack, JDK 11)
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: 'maven'

      - name: Show Java/Maven versions
        run: |
          java -version
          mvn -v

      - name: Build with Maven (module path)
        run: |
          mvn -B -DskipTests -f backpack-main/pom.xml clean package
          echo "== JARs found =="
          find backpack-main -maxdepth 3 -type f -name "*.jar" -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UltimateBackpack-jar
          path: backpack-main/target/*.jar
          if-no-files-found: error
