name: Build (Java 8 / Spigot 1.16.5)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: UltimateBackpack-${{ github.sha }}-jar
          path: target/UltimateBackpack-*.jar
